export const reducerCases ={
    SET_TOKEN:"SET_TOKEN",
    SET_PLAYLISTS:"SET_PLAYLISTS",
    SET_USER:"SET_USER",
    SET_NEW_RELEASES:"SET_NEW_RELEASES",
    SET_ALBUMS:'SET_ALBUMS',
    SET_ARTISTS:'SET_ARTISTS',
    SET_TRACKS:'SET_TRACKS',
    SET_SELECTEDPLAYLIST: "SET_SELECTEDPLAYLIST",
    SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
    SET_SONG_ID:'SET_SONG_ID',
    SET_SELECTEDSONG:"SET_SELECTEDSONG",
    SET_CREATEPLAYLISTS:"SET_CREATEPLAYLISTS",
    SET_SONGURI:"SET_SONGURI",
    SET_GENRES:"SET_GENRES"
}